#!/usr/bin/expect

set timeout -1

set count [lindex $argv 0]
if {$count == ""} {
    puts "Needs to specify a count as first parameter."
    exit 1
}

spawn /quartus/setup.sh

expect "Press \\\[Enter\\\] to continue:" { send "\r" }
expect "Press \\\[Enter\\\] to continue:" { send "\r" }

puts "----------------------------------"

while {$count > 0 } {
    expect "Press \\\[Enter\\\] to continue:" { send "\r" }
    puts "\n\ncount : $count\n\n";
    set count [expr $count-1];
}

expect "Do you accept this license? \\\[y/n\\\]" { send "y\r" }
expect "Installation directory \\\[/root/intelFPGA_lite" { send "/opt/intelFPGA_lite/\r" }
expect "Quartus Prime Lite Edition (Free)  \\\[Y/n\\\] :" { send "y\r" }
expect "Quartus Prime Lite Edition (Free)  - Quartus Prime Help" { send "n\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices \\\[Y/n\\\] :" { send "y\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - Arria II" { send "n\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - Cyclone IV" { send "n\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - Cyclone 10" { send "n\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - Cyclone V" { send "y\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - MAX II/V" { send "n\r" }
expect "Quartus Prime Lite Edition (Free)  - Devices - MAX 10 FPGA" { send "n\r" }
expect "ModelSim - Intel FPGA Starter Edition (Free)" { send "n\r" }
expect "ModelSim - Intel FPGA Edition" { send "n\r" }
expect "Is the selection above correct? \\\[Y/n\\\]:" { send "y\r" }
expect "Create shortcuts on Desktop \\\[Y/n\\\]:" { send "n\r" }
expect "Launch Quartus Prime Lite Edition \\\[Y/n\\\]:" { send "n\r" }
expect "Provide your feedback at" { send "N\r" }

close $spawn_id

exit 0
